#!/bin/bash

# Publishes the endpoint for this gear. Output format = $uuid@$dns:$appname

# Exit on any errors
set -e

# Get gear ip address.
gip=$(facter ipaddress);

#
# Publish this gear's endpoint.
# 
echo "${OPENSHIFT_GEAR_UUID}@${gip}:fabric8;$OPENSHIFT_GEAR_DNS"
